# Generated by Django 4.1.3 on 2022-11-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_group_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='capacity',
            field=models.IntegerField(default=3),
        ),
    ]
